version: '1.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Facu556
      MYSQL_DATABASE: Pruebas
      MYSQL_USER: facusj
      MYSQL_PASSWORD: Facu556
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Facu556
    ports:
      - "8080:80"
